image:
  - Visual Studio 2022

environment:
  matrix:
    - LIB_TYPE: shared
      CONFIG: x86_64
      CC: clang
      THREADING: openmp
      CBLAS: no

    - LIB_TYPE: shared
      CONFIG: haswell
      CC: clang
      THREADING: openmp
      CBLAS: no

install:
  - git submodule update --init --recursive
  - cd blis
  - set "PATH=C:\msys64\mingw64\bin;C:\msys64\bin;%PATH%"
  - if [%CC%]==[clang] set "PATH=C:\Program Files\LLVM\bin;%PATH%"
  - if [%CC%]==[clang] set "AR=llvm-ar"
  - if [%CC%]==[clang] set "AS=llvm-as"
  - if [%CC%]==[clang] call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64

build_script:
  - if [%LIB_TYPE%]==[shared] set "CONFIGURE_OPTS=%CONFIGURE_OPTS% --enable-shared --disable-static"
  - if [%LIB_TYPE%]==[static] set "CONFIGURE_OPTS=%CONFIGURE_OPTS% --disable-shared --enable-static"
  - if not [%CBLAS%]==[no] set "CONFIGURE_OPTS=%CONFIGURE_OPTS% --enable-cblas"
  - set RANLIB=echo
  - set LIBPTHREAD=
  - set "PATH=%PATH%;C:\blis\lib"
  - set "CFLAGS=-Wno-macro-redefined"
  - bash -lc "cd /c/projects/cython-blas/blis && ./configure %CONFIGURE_OPTS% --enable-threading=%THREADING% --enable-arg-max-hack --prefix=/c/blis %CONFIG%"
  - bash -lc "cd /c/projects/cython-blas/blis && mingw32-make -j4 V=1"
  - bash -lc "cd /c/projects/cython-blas/blis && mingw32-make install"
  - 7z a "C:\blis_%CONFIG%.zip" C:\blis
  - ps: Push-AppveyorArtifact "C:\blis_$Env:CONFIG.zip"
